/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Student;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Complaints.AllComplaintsJPanel;
import userinterface.Complaints.ComplaintJPanel;
import userinterface.Complaints.FileAComplaintJPanel;

/**
 *
 * @author aamrah
 */
public class StudentJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form StudentJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    
    public StudentJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) 
    {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRaiseComplaint = new javax.swing.JButton();
        btnAllComplaints = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnRaiseComplaint.setText("Raise a Complaint");
        btnRaiseComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseComplaintActionPerformed(evt);
            }
        });
        add(btnRaiseComplaint);
        btnRaiseComplaint.setBounds(244, 196, 170, 29);

        btnAllComplaints.setText("View All Complaints");
        btnAllComplaints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllComplaintsActionPerformed(evt);
            }
        });
        add(btnAllComplaints);
        btnAllComplaints.setBounds(244, 259, 170, 29);

        btnBack.setText("< Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(6, 23, 108, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaiseComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseComplaintActionPerformed
        // TODO add your handling code here:
        
        ComplaintJPanel complaintForm = new ComplaintJPanel(userProcessContainer, account,system);
        userProcessContainer.add("Complaint", complaintForm);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRaiseComplaintActionPerformed

    private void btnAllComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllComplaintsActionPerformed
        // TODO add your handling code here:
        
        AllComplaintsJPanel allcomplaints = new AllComplaintsJPanel(userProcessContainer, account, system);
        userProcessContainer.add("AllComplaints", allcomplaints);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAllComplaintsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllComplaints;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRaiseComplaint;
    // End of variables declaration//GEN-END:variables
}
