/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Signup;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Role.AdvisorRole;
import Business.Role.ChiefOfficerRole;
import Business.Role.DoctorRole;
import Business.Role.DriverRole;
import Business.Role.OUECCoordinatorRole;
import Business.Role.OUECInvestigatorRole;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Role.PoliceOfficerRole;
import Business.Role.PresidentRole;
import Business.Role.ReceptionistRole;
import Business.Role.StudentRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.util.regex.Pattern;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class EmployeeSignupJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system; 
    EnterpriseDirectory enterpriseDirectory;
    Enterprise NUPDEnterprise, OUECEnterprise, UHCSEnterprise, RedeyeEnterprise;

    /**
     * Creates new form EmployeeSignup
     */
    public EmployeeSignupJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        enterpriseDirectory=system.getEnterpriseDirectory();
//        if(enterpriseDirectory!=null)
        try{
            NUPDEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.NUPDEnterprise);
            OUECEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.OUECEnterprise);
            UHCSEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.UHCSEnterprise);
            RedeyeEnterprise=enterpriseDirectory.getEnterprise(Enterprise.EnterpriseType.RedeyeEnterprise);
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, " ED is empty");
        }
        
        
        String[] orgArray = {"--Select--", "NUPDEnterprise","OUECEnterprise", "RedeyeEnterprise", "UHCSEnterprise"};
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(orgArray);
        comboOrg.setModel( model );
    }
    
//    private EmployeeSignupJPanel() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uNameTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboOrg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtneuid = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });
        add(closeJButton);
        closeJButton.setBounds(819, 6, 79, 29);

        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(140, 230, 106, 16);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        add(PasswordField);
        PasswordField.setBounds(370, 220, 144, 26);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE SIGNUP ");
        add(jLabel1);
        jLabel1.setBounds(180, 60, 440, 26);

        jLabel5.setText("Username");
        add(jLabel5);
        jLabel5.setBounds(140, 180, 62, 20);

        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField);
        nameJTextField.setBounds(370, 140, 144, 26);

        jLabel3.setText("Name");
        add(jLabel3);
        jLabel3.setBounds(140, 150, 36, 16);

        uNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameTextFieldActionPerformed(evt);
            }
        });
        add(uNameTextField);
        uNameTextField.setBounds(370, 180, 144, 26);

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(400, 590, 88, 29);

        jLabel2.setText("Email id");
        add(jLabel2);
        jLabel2.setBounds(150, 280, 103, 16);

        jLabel6.setText("NEU id");
        add(jLabel6);
        jLabel6.setBounds(150, 330, 42, 16);

        jLabel7.setText("Contact Number");
        add(jLabel7);
        jLabel7.setBounds(150, 380, 103, 16);

        comboOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrgActionPerformed(evt);
            }
        });
        add(comboOrg);
        comboOrg.setBounds(340, 410, 96, 27);

        jLabel8.setText("Organisation");
        add(jLabel8);
        jLabel8.setBounds(150, 420, 81, 16);

        jLabel9.setText("Role");
        add(jLabel9);
        jLabel9.setBounds(150, 460, 27, 16);

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });
        add(comboRole);
        comboRole.setBounds(340, 460, 96, 27);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail);
        txtEmail.setBounds(370, 280, 144, 26);

        txtneuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtneuidActionPerformed(evt);
            }
        });
        add(txtneuid);
        txtneuid.setBounds(370, 330, 144, 26);

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone);
        txtPhone.setBounds(370, 370, 144, 26);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel10.setText("Only alphabets");
        add(jLabel10);
        jLabel10.setBounds(570, 150, 94, 16);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel11.setText("minimum length 5 and a number");
        add(jLabel11);
        jLabel11.setBounds(570, 190, 220, 16);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel12.setText("1 alphabet, 1 number, 1 !.*?");
        add(jLabel12);
        jLabel12.setBounds(570, 230, 206, 16);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel13.setText("exact 9 digits");
        add(jLabel13);
        jLabel13.setBounds(570, 330, 86, 16);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel14.setText("exact 10 digits");
        add(jLabel14);
        jLabel14.setBounds(570, 380, 94, 16);

        jLabel15.setText("Address");
        add(jLabel15);
        jLabel15.setBounds(150, 520, 51, 16);

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress);
        txtAddress.setBounds(340, 510, 220, 26);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel16.setText("*All fields are mandatory");
        add(jLabel16);
        jLabel16.setBounds(350, 560, 173, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void uNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameTextFieldActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String name = nameJTextField.getText();
        String uname=uNameTextField.getText();
        String password=PasswordField.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String neuid = txtneuid.getText();
        String address = txtAddress.getText();
        String org = ("--Select--".equals(String.valueOf(comboOrg.getSelectedItem())))? null : String.valueOf(comboOrg.getSelectedItem());
        String role = ("--Select--".equals(String.valueOf(comboRole.getSelectedItem())))? null : String.valueOf(comboRole.getSelectedItem());

        try {
            if(name==null || name.length()<2 || Pattern.matches("^[A-Za-z]+(\\s[A-Za-z]+)*$", name)==false){
                throw new Exception("Name is mandatory and should be of pattern alphabets followed by space with alphabets");
            }
            if(uname==null || uname.length()<5){
                throw new Exception("Username is mandatory and is alphanumeric of minimum 5 lengths");
            }
            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(uname)==false) {
                throw new Exception("User Name already exists");
            }
            if(password==null || Pattern.matches("^(?=(.*[a-z]){1,})(?=(.*[\\d]){1,})(?=(.*[\\W]){1,})(?!.*\\s).{5,30}$", password)==false){
                throw new Exception("Password is mandatory and of minimum 5 length with  atleast 1 alphabet, 1 number, 1 from ?!.*");
            }
            if(email==null || Pattern.matches("^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,3})+)$", email)==false){
                throw new Exception("Email is mandatory and of minimum 5 length with  atleast 1 alphabet, 1 number, 1 from ?!.*");
            }
            if(phone==null || Pattern.matches("^\\d{10}$", phone)==false){
                throw new Exception("Phone is mandatory and of exact 10 numbers");
            }
            if(neuid==null || Pattern.matches("^\\d{9}$", neuid)==false){
                throw new Exception("Neuid is mandatory and of exact 9 numbers");
            }
            if(address==null || Pattern.matches("^[A-Za-z]+(\\s[A-Za-z]+)*$", address)==false){
                throw new Exception("Address is mandatory");
            }
            if (org==null) {
                JOptionPane.showMessageDialog(null,"Org is mandatory");
            }
            if (role==null) {
                JOptionPane.showMessageDialog(null,"Role is mandatory");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

            return;
        } 
            //"PoliceOfficer","ChiefOfficer","OUECCoordinator","OUECInvestigator", "President","Driver","Doctor","Receptionist", "Advisor"
//              if ("PoliceOfficer".equals(role) )
//              {
//                  if(NUPDEnterprise!=null)
//                    {
//                        NUPDEnterprise.getOrganisationDirectory().getOrganisationList();
//                    }
//              }
           Employee e = system.getEmployeeDirectory().createEmployee(name, uname, password, address, phone, email, neuid);
           
           if ("PoliceOfficer".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new PoliceOfficerRole());
                system.getPoliceDirectory().createPoliceOfficer(name, uname, password, address, phone, email, neuid);
            } else if ("ChiefOfficer".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new ChiefOfficerRole());
                //no separate already in userAccount above line
            } else if ("OUECCoordinator".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new OUECCoordinatorRole());
                system.getOuecCoordinators().createOUECCoordinator(e);
            } else if ("OUECInvestigator".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new OUECInvestigatorRole());
                system.getInvestigatorDirectory().createOUECInvestigator(e);
            } else if ("President".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new PresidentRole());
                //no separate already in userAccount above line
            }  else if ("Driver".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new DriverRole());
                system.getDriverDirectory().createDriver(e);
            } else if ("Doctor".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new DoctorRole());
                system.getDoctorDirectory().createDoctor(e);
            } else if ("Receptionist".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new ReceptionistRole());
                //no separate already in userAccount above line
            } else if ("Advisor".equals(role)) {
                system.getUserAccountDirectory().createUserAccount(name,uname,password, e, new AdvisorRole());
                system.getAdvisorDirectory().createAdvisor(e);
            }

            JOptionPane.showMessageDialog(null,"You may now proceed to login!");

            nameJTextField.setText("");
            uNameTextField.setText("");
            PasswordField.setText("");
            txtAddress.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtneuid.setText("");
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void comboOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrgActionPerformed

        String org = ("--Select--".equals(String.valueOf(comboOrg.getSelectedItem())))? null : String.valueOf(comboOrg.getSelectedItem());
        if (org!=null) {

            if ("NUPDEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "PoliceOfficer","ChiefOfficer"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole.setModel( model );
            } else if ("OUECEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "OUECCoordinator","OUECInvestigator", "President"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole.setModel( model );
            } else if ("RedeyeEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "Driver"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole.setModel( model );
            } else if ("UHCSEnterprise".equals(org)) {
                String[] roleArray = {"--Select--", "Doctor","Receptionist", "Advisor"};
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(roleArray);
                comboRole.setModel( model );
            }
        }
    }//GEN-LAST:event_comboOrgActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoleActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtneuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtneuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtneuidActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton closeJButton;
    private javax.swing.JComboBox<String> comboOrg;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtneuid;
    private javax.swing.JTextField uNameTextField;
    // End of variables declaration//GEN-END:variables
}
