/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Signup;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class ManageSignupJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageSignup
     */
    public ManageSignupJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
    }
    private ManageSignupJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudentSignup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEmployeeSignup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnStudentSignup.setBackground(new java.awt.Color(0, 153, 153));
        btnStudentSignup.setText("Student Signup");
        btnStudentSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSignupActionPerformed(evt);
            }
        });
        add(btnStudentSignup);
        btnStudentSignup.setBounds(129, 180, 151, 29);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Are you new to this system?");
        add(jLabel3);
        jLabel3.setBounds(244, 114, 189, 16);

        btnEmployeeSignup.setBackground(new java.awt.Color(0, 153, 153));
        btnEmployeeSignup.setText("Employee Signup");
        btnEmployeeSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeSignupActionPerformed(evt);
            }
        });
        add(btnEmployeeSignup);
        btnEmployeeSignup.setBounds(388, 180, 151, 29);

        jLabel5.setText("If you are employee");
        add(jLabel5);
        jLabel5.setBounds(397, 152, 123, 16);

        closeJButton.setBackground(new java.awt.Color(0, 153, 153));
        closeJButton.setText("Close and Proceed to Login");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });
        add(closeJButton);
        closeJButton.setBounds(224, 270, 215, 29);

        jLabel4.setText("if you are Student");
        add(jLabel4);
        jLabel4.setBounds(144, 152, 111, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSignupActionPerformed

        StudentSignupJPanel studentSignupJPanel = new StudentSignupJPanel( userProcessContainer,  system);
        userProcessContainer.add("studentSignupJPanel", studentSignupJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudentSignupActionPerformed

    private void btnEmployeeSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeSignupActionPerformed

        EmployeeSignupJPanel employeeSignupJPanel = new EmployeeSignupJPanel( userProcessContainer,  system);
        userProcessContainer.add("employeeSignupJPanel", employeeSignupJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEmployeeSignupActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        if (componentArray.length>0) {
            Component component = componentArray[componentArray.length - 1];
        }
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_closeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeSignup;
    private javax.swing.JButton btnStudentSignup;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
