/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Complaints;

import Business.EcoSystem;
import Business.Student.Student;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author fianrodrigues
 */
public class FileAComplaintJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form FileAComplaintJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    String reasons="";
    
    public FileAComplaintJPanel(JPanel userProcessContainer, EcoSystem system) 
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        system.getStudentDirectory().createStudent("fifi", "fifi", "fifi", "2 Wiggles", "9819802928", "fifi29@gmail.com", "001991872");
        system.getStudentDirectory().createStudent("john", "john", "john", "5 Wiggles", "9819902928", "john11@gmail.com", "201991872");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lbTypeOfIncident = new javax.swing.JLabel();
        cmbTypeOfIncident1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblTitle3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbVictimName = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbAccusedName = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        chckRace = new javax.swing.JCheckBox();
        chckGender = new javax.swing.JCheckBox();
        chckNationality = new javax.swing.JCheckBox();
        lblTitle = new javax.swing.JLabel();
        chckPoliticalAffiliation = new javax.swing.JCheckBox();
        lbDateOfIncident = new javax.swing.JLabel();
        chckOrientation = new javax.swing.JCheckBox();
        txtDateOfIncident = new javax.swing.JTextField();
        chckDisability = new javax.swing.JCheckBox();
        lbTimeOfIncident = new javax.swing.JLabel();
        chckParentalStatus = new javax.swing.JCheckBox();
        txtTimeOfIncident = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        chckAge = new javax.swing.JCheckBox();

        lbLocation.setText("Location:");

        lbTypeOfIncident.setText("Type of Incident:");

        cmbTypeOfIncident1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Alleged Accusation", "Assault", "Discrimination", "Plaigiarism" }));
        cmbTypeOfIncident1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeOfIncident1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Describe the Incident:");

        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Details of the Involved Parties");

        jLabel3.setText("Name of the Victim:");

        cmbVictimName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "  ", "   ", "   " }));
        cmbVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVictimNameActionPerformed(evt);
            }
        });

        jLabel11.setText("Name of the Accused:");

        cmbAccusedName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "   ", "  ", " " }));
        cmbAccusedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccusedNameActionPerformed(evt);
            }
        });

        jLabel14.setText("What was the nature of the discrimination?");

        chckRace.setText("Race");
        chckRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckRaceActionPerformed(evt);
            }
        });

        chckGender.setText("Gender");
        chckGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckGenderActionPerformed(evt);
            }
        });

        chckNationality.setText("Nationality");
        chckNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckNationalityActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("FILE A COMPLAINT");

        chckPoliticalAffiliation.setText("Political Affiliation");
        chckPoliticalAffiliation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckPoliticalAffiliationActionPerformed(evt);
            }
        });

        lbDateOfIncident.setText("Date of Incident:");

        chckOrientation.setText("Orientation");
        chckOrientation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckOrientationActionPerformed(evt);
            }
        });

        chckDisability.setText("Disability");
        chckDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckDisabilityActionPerformed(evt);
            }
        });

        lbTimeOfIncident.setText("Time of Incident:");

        chckParentalStatus.setText("Parental Status");
        chckParentalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckParentalStatusActionPerformed(evt);
            }
        });

        txtTimeOfIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeOfIncidentActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Details of the Incident");

        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        chckAge.setText("Age");
        chckAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(chckAge)
                .addContainerGap(825, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbDateOfIncident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTimeOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTypeOfIncident, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtTimeOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbAccusedName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbTypeOfIncident1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtDateOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(30, 30, 30)
                                            .addComponent(cmbVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(15, 15, 15))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addComponent(chckParentalStatus)
                                            .addGap(18, 18, 18)
                                            .addComponent(chckRace)
                                            .addGap(18, 18, 18)
                                            .addComponent(chckGender))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chckPoliticalAffiliation)
                                            .addGap(18, 18, 18)
                                            .addComponent(chckOrientation)
                                            .addGap(18, 18, 18)
                                            .addComponent(chckDisability))
                                        .addComponent(chckNationality))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(321, 321, 321)
                            .addComponent(btnSubmit)
                            .addGap(52, 52, 52)
                            .addComponent(btnBack)))
                    .addGap(5, 5, 5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addComponent(chckAge)
                .addGap(246, 246, 246))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDateOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDateOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cmbVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTimeOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimeOfIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cmbAccusedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbTypeOfIncident)
                        .addComponent(cmbTypeOfIncident1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chckParentalStatus)
                        .addComponent(chckRace)
                        .addComponent(chckGender))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chckPoliticalAffiliation)
                        .addComponent(chckOrientation)
                        .addComponent(chckDisability))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chckNationality)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSubmit)
                        .addComponent(btnBack))
                    .addGap(40, 40, 40)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chckRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckRaceActionPerformed
        // TODO add your handling code here:

        if(chckRace.isEnabled())
        {
            reasons += " Race ";
        }

    }//GEN-LAST:event_chckRaceActionPerformed

    private void chckGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckGenderActionPerformed
        // TODO add your handling code here:

        if(chckGender.isEnabled())
        {
            reasons += " Gender ";
        }
    }//GEN-LAST:event_chckGenderActionPerformed

    private void chckNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckNationalityActionPerformed
        // TODO add your handling code here:

        if(chckNationality.isEnabled())
        {
            reasons += " Nationality ";
        }
    }//GEN-LAST:event_chckNationalityActionPerformed

    private void chckPoliticalAffiliationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckPoliticalAffiliationActionPerformed
        // TODO add your handling code here:

        if(chckPoliticalAffiliation.isEnabled())
        {
            reasons+=" Political Affiliation ";
        }
    }//GEN-LAST:event_chckPoliticalAffiliationActionPerformed

    private void chckOrientationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckOrientationActionPerformed
        // TODO add your handling code here:

        if (chckOrientation.isEnabled())
        {
            reasons += " Orientation ";
        }
    }//GEN-LAST:event_chckOrientationActionPerformed

    private void chckDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckDisabilityActionPerformed
        // TODO add your handling code here:

        if(chckDisability.isEnabled())
        {
            reasons += " Disability ";
        }
    }//GEN-LAST:event_chckDisabilityActionPerformed

    private void chckParentalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckParentalStatusActionPerformed
        // TODO add your handling code here:

        if (chckParentalStatus.isEnabled())
        {
            reasons += " Parental Status ";

        }

    }//GEN-LAST:event_chckParentalStatusActionPerformed

    private void txtTimeOfIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeOfIncidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeOfIncidentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void chckAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckAgeActionPerformed
        // TODO add your handling code here:
        
         if(chckRace.isEnabled())
        {
            reasons += " Race ";
        }
    }//GEN-LAST:event_chckAgeActionPerformed

    private void cmbVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVictimNameActionPerformed
        // TODO add your handling code here:
        ArrayList<Student> victimStudentList = system.getStudentDirectory().getStudentDir();
        DefaultComboBoxModel model= new DefaultComboBoxModel(victimStudentList.toArray());
        cmbVictimName.setModel( model );
        
    }//GEN-LAST:event_cmbVictimNameActionPerformed

    private void cmbTypeOfIncident1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeOfIncident1ActionPerformed
        // TODO add your handling code here:
        
        String org = ("--Select--".equals(String.valueOf(cmbTypeOfIncident1.getSelectedItem())))? null : String.valueOf(cmbTypeOfIncident1.getSelectedItem());
        if (org!=null) 
        {

            if ("Alleged Accusation".equals(org)) 
            {
//              go to the next page
            } 
            else if ("Assault".equals(org))
            {
//                go to the next page
            }
            else if ("Discrimination".equals(org)) 
            {
//               go to the next page
            }
            else if ("Plaigiarism".equals(org))
            {
//                go to the next page
            }
        }
    }//GEN-LAST:event_cmbTypeOfIncident1ActionPerformed

    private void cmbAccusedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccusedNameActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Student> accusedStudentList = system.getStudentDirectory().getStudentDir();
        DefaultComboBoxModel model= new DefaultComboBoxModel(accusedStudentList.toArray());
        cmbAccusedName.setModel( model );
        
    }//GEN-LAST:event_cmbAccusedNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chckAge;
    private javax.swing.JCheckBox chckDisability;
    private javax.swing.JCheckBox chckGender;
    private javax.swing.JCheckBox chckNationality;
    private javax.swing.JCheckBox chckOrientation;
    private javax.swing.JCheckBox chckParentalStatus;
    private javax.swing.JCheckBox chckPoliticalAffiliation;
    private javax.swing.JCheckBox chckRace;
    private javax.swing.JComboBox<String> cmbAccusedName;
    private javax.swing.JComboBox<String> cmbTypeOfIncident1;
    private javax.swing.JComboBox<String> cmbVictimName;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbDateOfIncident;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbTimeOfIncident;
    private javax.swing.JLabel lbTypeOfIncident;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextField txtDateOfIncident;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTimeOfIncident;
    // End of variables declaration//GEN-END:variables
}
