/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.UHCS;

import Business.Complaint.Complaint;
import Business.EcoSystem;
import Business.Logic.UHCS.Doctor;
import Business.Logic.UHCS.DoctorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class AssignDoctorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    Complaint complaintWorkRequest;
    EcoSystem system;
    
    /**
     * Creates new form AssignDoctorJPanel
     */
    public AssignDoctorJPanel(JPanel userProcessContainer, UserAccount account, Complaint complaintWorkRequest, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.complaintWorkRequest = complaintWorkRequest;
        this.system = system;
        initComponents();
        
        lblComplaintId.setText(complaintWorkRequest.getComplaintID());
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel md=(DefaultTableModel)tblDoctorList.getModel();
        md.setRowCount(0);
        Object row[]= new Object[3];
        
        //taking network, enterprise level doctor list
        ArrayList<Doctor> doctorList  = system.getDoctorDirectory().getDoctorList();
        for (Doctor doctor : doctorList) {
            row[0] = doctor; //username gets printed
            row[1] = doctor.getEmployee().getName();
            row[2] = doctor.getEmployee().isIsFree();  //true false
                             
            md.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblComplaintId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        tblDoctorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor UserName", "Doctor Name", "isFree?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoctorList);

        jLabel3.setText("Complaint ID:");

        jLabel2.setText("For the selected:");

        jLabel1.setText("Assign Doctor");

        btnBack.setText("<-- Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnBack)
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lblComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(btnAssign)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(lblComplaintId, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAssign)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedRow = tblDoctorList.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a doctor from the table to assign","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Doctor doctor  = (Doctor)tblDoctorList.getValueAt(selectedRow, 0);
        boolean isFree = (boolean) tblDoctorList.getValueAt(selectedRow, 2);
            
            if(!isFree) {
                JOptionPane.showMessageDialog(null,"Sorry selected doctor is not free, select another doctor who is free","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //Set status of complaint 
            complaintWorkRequest.setStatus("UHCS Doctor Assigned");
            
            //set DoctorName on complaint
            //complaintWorkRequest.setDoctor(doctor.getEmployee().getUsername());
            
            //assign it in enterprise level doctor object
            doctor.setComplaint(complaintWorkRequest);
            //doctor.getCompletedComplaintsList().add(complaintWorkRequest);
            //make doctor busy
            doctor.getEmployee().setIsFree(false);
            
            //assign it in userAccount level of doctor (to do on signup)
            UserAccount doctorUserAccount = system.getUserAccountDirectory().fetchUaWithUserName(doctor.getEmployee().getUsername());
            doctorUserAccount.getWorkQueue().getComplaintList().add(complaintWorkRequest);
            //make ua busy
            doctorUserAccount.getEmployee().setIsFree(false);
            
            JOptionPane.showMessageDialog(null,"Complaint with id: "+ complaintWorkRequest.getComplaintID() +"is assigned to Doctor "+doctor.getEmployee().getName());
                    
            // clear table
            DefaultTableModel model = (DefaultTableModel) tblDoctorList.getModel();
            model.setRowCount(0);
        
            //back page
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);

        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        // clear table
        DefaultTableModel model = (DefaultTableModel) tblDoctorList.getModel();
        model.setRowCount(0);

        //back page
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaintId;
    private javax.swing.JTable tblDoctorList;
    // End of variables declaration//GEN-END:variables
}
