/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.UHCS;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vignesh Gunasekaran <gunasekaran.v@northeastern.edu>
 */
public class ManageAdvisorJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    
    /**
     * Creates new form ManageReceptionist
     */
    public ManageAdvisorJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;     // logged user; UserAccount has both Employee (basic details) & WorkQueue (complaintlist)
        this.system = system;
        
        lblName.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnInBucketPage = new javax.swing.JButton();
        btnOldPage = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME");
        add(jLabel1);
        jLabel1.setBounds(0, 60, 980, 26);
        add(lblName);
        lblName.setBounds(801, 24, 127, 26);

        btnInBucketPage.setText("Manage In-Bucket Complaints");
        btnInBucketPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBucketPageActionPerformed(evt);
            }
        });
        add(btnInBucketPage);
        btnInBucketPage.setBounds(390, 190, 234, 29);

        btnOldPage.setText("Manage Completed Complaints");
        btnOldPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldPageActionPerformed(evt);
            }
        });
        add(btnOldPage);
        btnOldPage.setBounds(380, 260, 240, 29);

        btnDashboard.setText("Dashboard View");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        add(btnDashboard);
        btnDashboard.setBounds(430, 340, 145, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        DashboardAdvisorJPanel page = new DashboardAdvisorJPanel(userProcessContainer,account,system);
        userProcessContainer.add("Advisor Dashboard Complaints",page);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnInBucketPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBucketPageActionPerformed
        AdvisorJPanel page = new AdvisorJPanel(userProcessContainer,account,system);
        userProcessContainer.add("Advisor InBucket Complaints",page);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInBucketPageActionPerformed

    private void btnOldPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldPageActionPerformed
        CompletedAdvisorJPanel page = new CompletedAdvisorJPanel(userProcessContainer,account,system);
        userProcessContainer.add("Advisor Old Complaints",page);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOldPageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInBucketPage;
    private javax.swing.JButton btnOldPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
