/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Redeye;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author fianrodrigues
 */
public class ThreatsOrStalkingStatusJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form ThreatsOrStalkingJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    
    public ThreatsOrStalkingStatusJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceptRide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOnTheWay = new javax.swing.JButton();
        btnSceneReached = new javax.swing.JButton();
        btnDroppedOffAtUHCS = new javax.swing.JButton();
        btnTaskCompleted = new javax.swing.JButton();
        btnSceneReached1 = new javax.swing.JButton();

        btnAcceptRide.setText("Accept Ride");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STATUS UPDATE FOR THREATS OR STALKING");

        btnOnTheWay.setText("On The Way");
        btnOnTheWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnTheWayActionPerformed(evt);
            }
        });

        btnSceneReached.setText("Scene Reached");
        btnSceneReached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSceneReachedActionPerformed(evt);
            }
        });

        btnDroppedOffAtUHCS.setText("Dropped Off At UHCS");
        btnDroppedOffAtUHCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDroppedOffAtUHCSActionPerformed(evt);
            }
        });

        btnTaskCompleted.setText("Task Completed");
        btnTaskCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskCompletedActionPerformed(evt);
            }
        });

        btnSceneReached1.setText("Picked Up The Victim");
        btnSceneReached1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSceneReached1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnAcceptRide)
                .addGap(172, 172, 172)
                .addComponent(btnOnTheWay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(btnSceneReached)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnSceneReached1)
                .addGap(135, 135, 135)
                .addComponent(btnDroppedOffAtUHCS)
                .addGap(337, 337, 337))
            .addGroup(layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(btnTaskCompleted))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSceneReached)
                    .addComponent(btnAcceptRide)
                    .addComponent(btnOnTheWay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDroppedOffAtUHCS)
                    .addComponent(btnSceneReached1))
                .addGap(84, 84, 84)
                .addComponent(btnTaskCompleted)
                .addGap(265, 265, 265))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnTheWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnTheWayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnTheWayActionPerformed

    private void btnSceneReachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSceneReachedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSceneReachedActionPerformed

    private void btnDroppedOffAtUHCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDroppedOffAtUHCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDroppedOffAtUHCSActionPerformed

    private void btnTaskCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskCompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaskCompletedActionPerformed

    private void btnSceneReached1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSceneReached1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSceneReached1ActionPerformed

    private void btnAcceptRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptRideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcceptRideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptRide;
    private javax.swing.JButton btnDroppedOffAtUHCS;
    private javax.swing.JButton btnOnTheWay;
    private javax.swing.JButton btnSceneReached;
    private javax.swing.JButton btnSceneReached1;
    private javax.swing.JButton btnTaskCompleted;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
